### PR TITLE
OrderedDict is in collections module in python-2.7+

### PR DESCRIPTION
**Pull request by tomspur**
Try to first import OrderedDict from the collections module and then from ordereddict module as a fall back.

See: http://docs.python.org/library/collections.html

### CODE REVIEW

**Comment by tomspur** [comment]
Still cannot get it to work over here (just wanted to give dexy a try...).

Is this a known issue?

```
$ dexy setup
Traceback (most recent call last):
  File "/home/tomspur/venv/tomspur_default/bin/dexy", line 8, in <module>
    load_entry_point('dexy==0.7.0', 'console_scripts', 'dexy')()
  File "$INSTPATH/dexy/commands.py", line 37, in run
    mod_name = command_class.__module__
AttributeError: 'NoneType' object has no attribute '__module__'
```

**Comment by ananelson** [comment]
Hi, Thomas,

Please try https://github.com/ananelson/dexy/tree/8f66d2fc423a5c1eea9bae118fd28efdf9f9ad55

I am in the middle of rewrites for 0.7.0 and lots of stuff is broken after that point.

Regarding the ordereddict/collections issue, I got tired of the try/catch statement taking up 4 LOC in every file and complicating my imports. Is there a huge performance benefit to using the 'collections' version for 2.7?

Thanks,
Ana

**Comment by tomspur** [comment]
Hi Ana,

ah, ok. I'd have expected that master is always working and a rewrite will happen in a branch ;)

Yeah, I can understand that the imports look quite cluttered... How about importing once, e.g. in a "common" module and import from there? Looks much better than before. I updated the commit/PR to reflect that.

There is no need for a ordereddict package, when you can use the OrderedDict from the python standard library (and that package doesn't exist in Fedora for that reason...).
So to be distribution independent and not rely on pip to automatically install the dependencies (e.g. the needless ordereddict package), some solution like the 2 proposed need to be implemented, I'm afraid....

Is the "common" solution more appealing?

The commit you are refering to at least doesn't crash right away. I'll give it a try. Thanks.

Greetings,
   Tom

**Comment by ananelson** [comment]
Have implemented this in latest commit, thanks for the patch.

**Pull request closed without merging**
